# Generated by Django 3.2.8 on 2021-11-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reposts',
            field=models.IntegerField(default=0),
        ),
    ]
